package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shubh
 */
public class additionalcourse extends javax.swing.JFrame {

    static String ncourses = "";
    static String nfee = "";
    static String npaid = "";
    static String ndues = "";
    static String ndate = "";
    static String nduration = "";

    public additionalcourse() {
        initComponents();
        myinitComponents();
        loadcourses();
    }

    private void loadcourses() {
        try {
            BufferedReader brr = new BufferedReader(new FileReader("courses.txt"));
            int j = Integer.parseInt(brr.readLine());
            for (int i = 0; i < j - 1; i++) {
                String cdta = brr.readLine();
                course6.addItem(cdta);
                course7.addItem(cdta);
                course8.addItem(cdta);
                course9.addItem(cdta);
                course10.addItem(cdta);
            }
            brr.close();
        } catch (Exception e) {
        }
    }
    
    private void myinitComponents(){
        feeerr.setVisible(false);
        paiderr.setVisible(false);
        dateerr.setVisible(false);
        durationerr.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paid7 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        d9YYYY = new javax.swing.JTextField();
        paid6 = new javax.swing.JTextField();
        d8YYYY = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        d6MM = new javax.swing.JTextField();
        d6DD = new javax.swing.JTextField();
        d6YYYY = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        d7DD = new javax.swing.JTextField();
        course6 = new javax.swing.JComboBox<>();
        jLabel70 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        d9MM = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        fee7 = new javax.swing.JTextField();
        fee6 = new javax.swing.JTextField();
        fee9 = new javax.swing.JTextField();
        course10 = new javax.swing.JComboBox<>();
        d7MM = new javax.swing.JTextField();
        d10YYYY = new javax.swing.JTextField();
        course7 = new javax.swing.JComboBox<>();
        duration6 = new javax.swing.JTextField();
        d10MM = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        duration8 = new javax.swing.JTextField();
        course8 = new javax.swing.JComboBox<>();
        paid8 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        d7YYYY = new javax.swing.JTextField();
        paid9 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        fee10 = new javax.swing.JTextField();
        d8DD = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        course9 = new javax.swing.JComboBox<>();
        jLabel75 = new javax.swing.JLabel();
        d9DD = new javax.swing.JTextField();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        duration10 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        duration9 = new javax.swing.JTextField();
        d10DD = new javax.swing.JTextField();
        d8MM = new javax.swing.JTextField();
        paid10 = new javax.swing.JTextField();
        fee8 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        duration7 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        dateerr = new javax.swing.JLabel();
        feeerr = new javax.swing.JLabel();
        durationerr = new javax.swing.JLabel();
        paiderr = new javax.swing.JLabel();

        setTitle("Additional Course selector");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(240, 300, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 100));
        setPreferredSize(new java.awt.Dimension(1070, 310));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paid7.setBackground(new Color (0,0,0,0));
        paid7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paid7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paid7.setToolTipText("");
        paid7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        paid7.setOpaque(false);
        jPanel1.add(paid7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 30));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel79.setText("  months");
        jPanel1.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 80, 30));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setText(" /");
        jPanel1.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 20, 40));

        d9YYYY.setBackground(new Color (0,0,0,0));
        d9YYYY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d9YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d9YYYY.setOpaque(false);
        jPanel1.add(d9YYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 168, 50, -1));

        paid6.setBackground(new Color (0,0,0,0));
        paid6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paid6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paid6.setToolTipText("");
        paid6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        paid6.setOpaque(false);
        jPanel1.add(paid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, 30));

        d8YYYY.setBackground(new Color (0,0,0,0));
        d8YYYY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d8YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d8YYYY.setOpaque(false);
        jPanel1.add(d8YYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 168, 50, -1));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel65.setText(" /");
        jPanel1.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 20, 40));

        d6MM.setBackground(new Color (0,0,0,0));
        d6MM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d6MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d6MM.setOpaque(false);
        jPanel1.add(d6MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 168, 20, -1));

        d6DD.setBackground(new Color (0,0,0,0));
        d6DD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d6DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d6DD.setOpaque(false);
        jPanel1.add(d6DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 168, 20, -1));

        d6YYYY.setBackground(new Color (0,0,0,0));
        d6YYYY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d6YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d6YYYY.setOpaque(false);
        jPanel1.add(d6YYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 168, 50, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setText("Course Fee               :");
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 30));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel62.setText("Fee Paid                   :");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 30));

        d7DD.setBackground(new Color (0,0,0,0));
        d7DD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d7DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d7DD.setOpaque(false);
        jPanel1.add(d7DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 168, 20, -1));

        course6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 6" }));
        jPanel1.add(course6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel70.setText(" /");
        jPanel1.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 20, 40));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setText(" /");
        jPanel1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 20, 40));

        d9MM.setBackground(new Color (0,0,0,0));
        d9MM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d9MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d9MM.setOpaque(false);
        jPanel1.add(d9MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 168, 20, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel77.setText("  months");
        jPanel1.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 80, 30));

        fee7.setBackground(new Color (0,0,0,0));
        fee7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fee7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fee7.setToolTipText("");
        fee7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fee7.setOpaque(false);
        jPanel1.add(fee7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 110, 30));

        fee6.setBackground(new Color (0,0,0,0));
        fee6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fee6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fee6.setToolTipText("");
        fee6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fee6.setOpaque(false);
        jPanel1.add(fee6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 110, 30));

        fee9.setBackground(new Color (0,0,0,0));
        fee9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fee9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fee9.setToolTipText("");
        fee9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fee9.setOpaque(false);
        jPanel1.add(fee9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 110, 30));

        course10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 10" }));
        jPanel1.add(course10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 110, -1));

        d7MM.setBackground(new Color (0,0,0,0));
        d7MM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d7MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d7MM.setOpaque(false);
        jPanel1.add(d7MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 168, 20, -1));

        d10YYYY.setBackground(new Color (0,0,0,0));
        d10YYYY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d10YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d10YYYY.setOpaque(false);
        jPanel1.add(d10YYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 168, 50, -1));

        course7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 7" }));
        jPanel1.add(course7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 110, -1));

        duration6.setBackground(new Color (0,0,0,0));
        duration6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duration6.setToolTipText("");
        duration6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        duration6.setOpaque(false);
        jPanel1.add(duration6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 30, 30));

        d10MM.setBackground(new Color (0,0,0,0));
        d10MM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d10MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d10MM.setOpaque(false);
        jPanel1.add(d10MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 168, 20, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setText("Date of Admission :");
        jPanel1.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, 40));

        duration8.setBackground(new Color (0,0,0,0));
        duration8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duration8.setToolTipText("");
        duration8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        duration8.setOpaque(false);
        jPanel1.add(duration8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 30, 30));

        course8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 8" }));
        jPanel1.add(course8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 110, -1));

        paid8.setBackground(new Color (0,0,0,0));
        paid8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paid8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paid8.setToolTipText("");
        paid8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        paid8.setOpaque(false);
        jPanel1.add(paid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 110, 30));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel67.setText(" /");
        jPanel1.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 20, 40));

        d7YYYY.setBackground(new Color (0,0,0,0));
        d7YYYY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d7YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d7YYYY.setOpaque(false);
        jPanel1.add(d7YYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 168, 50, -1));

        paid9.setBackground(new Color (0,0,0,0));
        paid9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paid9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paid9.setToolTipText("");
        paid9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        paid9.setOpaque(false);
        jPanel1.add(paid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 110, 30));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel72.setText(" /");
        jPanel1.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 20, 40));

        fee10.setBackground(new Color (0,0,0,0));
        fee10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fee10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fee10.setToolTipText("");
        fee10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fee10.setOpaque(false);
        jPanel1.add(fee10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 110, 30));

        d8DD.setBackground(new Color (0,0,0,0));
        d8DD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d8DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d8DD.setOpaque(false);
        jPanel1.add(d8DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 168, 20, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setText(" /");
        jPanel1.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 20, 40));

        course9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 9" }));
        jPanel1.add(course9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 110, -1));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel75.setText("  months");
        jPanel1.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 80, 30));

        d9DD.setBackground(new Color (0,0,0,0));
        d9DD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d9DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d9DD.setOpaque(false);
        jPanel1.add(d9DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 168, 20, -1));

        kButton2.setBorder(null);
        kButton2.setForeground(new java.awt.Color(204, 0, 0));
        kButton2.setText("Close");
        kButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton2.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkForeGround(new java.awt.Color(204, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(204, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(204, 204, 204));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 100, 30));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel64.setText("Course Duration     :");
        jPanel1.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel68.setText(" /");
        jPanel1.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 20, 40));

        duration10.setBackground(new Color (0,0,0,0));
        duration10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duration10.setToolTipText("");
        duration10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        duration10.setOpaque(false);
        jPanel1.add(duration10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 30, 30));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel60.setText("Select Course          :");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 30));

        duration9.setBackground(new Color (0,0,0,0));
        duration9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duration9.setToolTipText("");
        duration9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        duration9.setOpaque(false);
        jPanel1.add(duration9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 30, 30));

        d10DD.setBackground(new Color (0,0,0,0));
        d10DD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d10DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d10DD.setOpaque(false);
        jPanel1.add(d10DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 168, 20, -1));

        d8MM.setBackground(new Color (0,0,0,0));
        d8MM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d8MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        d8MM.setOpaque(false);
        jPanel1.add(d8MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 168, 20, -1));

        paid10.setBackground(new Color (0,0,0,0));
        paid10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paid10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paid10.setToolTipText("");
        paid10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        paid10.setOpaque(false);
        jPanel1.add(paid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 110, 30));

        fee8.setBackground(new Color (0,0,0,0));
        fee8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fee8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fee8.setToolTipText("");
        fee8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        fee8.setOpaque(false);
        jPanel1.add(fee8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 30));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel78.setText("  months");
        jPanel1.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 80, 30));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel66.setText(" /");
        jPanel1.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 20, 40));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setText(" /");
        jPanel1.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 20, 40));

        duration7.setBackground(new Color (0,0,0,0));
        duration7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        duration7.setToolTipText("");
        duration7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        duration7.setOpaque(false);
        jPanel1.add(duration7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 30, 30));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel76.setText("  months");
        jPanel1.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 80, 30));

        kButton3.setBorder(null);
        kButton3.setText("Done");
        kButton3.setDefaultCapable(false);
        kButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 170, 100, 30));

        dateerr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dateerr.setForeground(new java.awt.Color(204, 0, 0));
        dateerr.setText("*");
        jPanel1.add(dateerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 10, 30));

        feeerr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        feeerr.setForeground(new java.awt.Color(204, 0, 0));
        feeerr.setText("*");
        jPanel1.add(feeerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 10, 30));

        durationerr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        durationerr.setForeground(new java.awt.Color(204, 0, 0));
        durationerr.setText("*");
        jPanel1.add(durationerr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 10, 30));

        paiderr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paiderr.setForeground(new java.awt.Color(204, 0, 0));
        paiderr.setText("*");
        jPanel1.add(paiderr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 10, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        additionalcourse.this.hide();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        // done button
        myinitComponents();

        // check fee && paid && date && duration
        int checkerr = 0;

        if (course6.getSelectedItem() != "Course 6") {
            try {
                Integer.parseInt(fee6.getText());
                try {
                    if (Integer.parseInt(d6DD.getText()) > 0 && Integer.parseInt(d6DD.getText()) <= 31 && Integer.parseInt(d6MM.getText()) > 0 && Integer.parseInt(d6MM.getText()) <= 12 && d6YYYY.getText().length() == 4) {

                    } else {
                        dateerr.setVisible(true);
                        checkerr = 1;
                    }
                } catch (Exception e) {
                    dateerr.setVisible(true);
                    checkerr = 1;

                }
            } catch (Exception e) {
                feeerr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(paid6.getText());
            } catch (Exception e) {
                paiderr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(duration6.getText());
            } catch (Exception e) {
                checkerr = 1;
                durationerr.setVisible(true);
            }
        }

        if (course7.getSelectedItem() != "Course 7") {
            try {
                Integer.parseInt(fee7.getText());
                try {
                    if (Integer.parseInt(d7DD.getText()) > 0 && Integer.parseInt(d7DD.getText()) <= 31 && Integer.parseInt(d7MM.getText()) > 0 && Integer.parseInt(d7MM.getText()) <= 12 && d7YYYY.getText().length() == 4) {

                    } else {
                        dateerr.setVisible(true);
                        checkerr = 1;
                    }
                } catch (Exception e) {
                    dateerr.setVisible(true);
                    checkerr = 1;

                }
            } catch (Exception e) {
                feeerr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(paid7.getText());
            } catch (Exception e) {
                paiderr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(duration7.getText());
            } catch (Exception e) {
                checkerr = 1;
                durationerr.setVisible(true);
            }
        }

        if (course8.getSelectedItem() != "Course 8") {
            try {
                Integer.parseInt(fee8.getText());
                try {
                    if (Integer.parseInt(d8DD.getText()) > 0 && Integer.parseInt(d8DD.getText()) <= 31 && Integer.parseInt(d8MM.getText()) > 0 && Integer.parseInt(d8MM.getText()) <= 12 && d8YYYY.getText().length() == 4) {

                    } else {
                        dateerr.setVisible(true);
                        checkerr = 1;
                    }
                } catch (Exception e) {
                    dateerr.setVisible(true);
                    checkerr = 1;

                }
            } catch (Exception e) {
                feeerr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(paid8.getText());
            } catch (Exception e) {
                paiderr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(duration8.getText());
            } catch (Exception e) {
                checkerr = 1;
                durationerr.setVisible(true);
            }
        }

        if (course9.getSelectedItem() != "Course 9") {
            try {
                Integer.parseInt(fee9.getText());
                try {
                    if (Integer.parseInt(d9DD.getText()) > 0 && Integer.parseInt(d9DD.getText()) <= 31 && Integer.parseInt(d9MM.getText()) > 0 && Integer.parseInt(d9MM.getText()) <= 12 && d9YYYY.getText().length() == 4) {

                    } else {
                        dateerr.setVisible(true);
                        checkerr = 1;
                    }
                } catch (Exception e) {
                    dateerr.setVisible(true);
                    checkerr = 1;

                }
            } catch (Exception e) {
                feeerr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(paid9.getText());
            } catch (Exception e) {
                paiderr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(duration9.getText());
            } catch (Exception e) {
                checkerr = 1;
                durationerr.setVisible(true);
            }
        }

        if (course10.getSelectedItem() != "Course 10") {
            try {
                Integer.parseInt(fee10.getText());
                try {
                    if (Integer.parseInt(d10DD.getText()) > 0 && Integer.parseInt(d10DD.getText()) <= 31 && Integer.parseInt(d10MM.getText()) > 0 && Integer.parseInt(d10MM.getText()) <= 12 && d10YYYY.getText().length() == 4) {

                    } else {
                        dateerr.setVisible(true);
                        checkerr = 1;
                    }
                } catch (Exception e) {
                    dateerr.setVisible(true);
                    checkerr = 1;

                }
            } catch (Exception e) {
                feeerr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(paid10.getText());
            } catch (Exception e) {
                paiderr.setVisible(true);
                checkerr = 1;

            }
            try {
                Integer.parseInt(duration10.getText());
            } catch (Exception e) {
                checkerr = 1;
                durationerr.setVisible(true);
            }
        }

        // final save
        if (checkerr == 0) {
            String spaces = "  ";

            if (course6.getSelectedItem() != "Course 6") {
                String tempc = "";
                String tempf = "";
                String tempp = "";
                String tempd = "";
                String tempdate = "";
                String tempduration = "";
                tempc = (String) course6.getSelectedItem();
                tempf = fee6.getText();
                tempp = paid6.getText();
                tempd = String.valueOf(Integer.parseInt(fee6.getText()) - Integer.parseInt(paid6.getText()));
                tempdate = d6DD.getText() + "/" + d6MM.getText() + "/" + d6YYYY.getText();
                tempduration = duration6.getText() + " " + "months";
                int courselen = tempc.length();
                int feelen = tempf.length();
                int paidlen = tempp.length();
                int dueslen = tempd.length();
                int datelen = tempdate.length();
                int durationlen = tempduration.length();
                int maxlen = Math.max(courselen, feelen);
                maxlen = Math.max(maxlen, paidlen);
                maxlen = Math.max(maxlen, dueslen);
                maxlen = Math.max(maxlen, datelen);
                maxlen = Math.max(maxlen, durationlen);
                String minspaces = "";
                if (courselen < maxlen) {
                    int len = maxlen - courselen;
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ncourses = ncourses + spaces + tempc + minspaces + spaces + "|";
                } else {
                    ncourses = ncourses + spaces + tempc + spaces + "|";
                }
                if (feelen < maxlen) {
                    int len = maxlen - feelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nfee = nfee + spaces + tempf + minspaces + spaces + "|";
                } else {
                    nfee = nfee + spaces + tempf + spaces + "|";
                }
                if (paidlen < maxlen) {
                    int len = maxlen - paidlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    npaid = npaid + spaces + tempp + minspaces + spaces + "|";
                } else {
                    npaid = npaid + spaces + tempp + spaces + "|";
                }
                if (dueslen < maxlen) {
                    int len = maxlen - dueslen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndues = ndues + spaces + tempd + minspaces + spaces + "|";
                } else {
                    ndues = ndues + spaces + tempd + spaces + "|";
                }
                if (datelen < maxlen) {
                    int len = maxlen - datelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndate = ndate + spaces + tempdate + minspaces + spaces + "|";
                } else {
                    ndate = ndate + spaces + tempdate + spaces + "|";
                }
                if (durationlen < maxlen) {
                    int len = maxlen - durationlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nduration = nduration + spaces + tempduration + minspaces + spaces + "|";
                } else {
                    nduration = nduration + spaces + tempduration + spaces + "|";
                }
            }
            if (course7.getSelectedItem() != "Course 7") {
                String tempc = "";
                String tempf = "";
                String tempp = "";
                String tempd = "";
                String tempdate = "";
                String tempduration = "";
                tempc = (String) course7.getSelectedItem();
                tempf = fee7.getText();
                tempp = paid7.getText();
                tempd = String.valueOf(Integer.parseInt(fee7.getText()) - Integer.parseInt(paid7.getText()));
                tempdate = d7DD.getText() + "/" + d7MM.getText() + "/" + d7YYYY.getText();
                tempduration = duration7.getText() + " " + "months";
                int courselen = tempc.length();
                int feelen = tempf.length();
                int paidlen = tempp.length();
                int dueslen = tempd.length();
                int datelen = tempdate.length();
                int durationlen = tempduration.length();
                int maxlen = Math.max(courselen, feelen);
                maxlen = Math.max(maxlen, paidlen);
                maxlen = Math.max(maxlen, dueslen);
                maxlen = Math.max(maxlen, datelen);
                maxlen = Math.max(maxlen, durationlen);
                String minspaces = "";
                if (courselen < maxlen) {
                    int len = maxlen - courselen;
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ncourses = ncourses + spaces + tempc + minspaces + spaces + "|";
                } else {
                    ncourses = ncourses + spaces + tempc + spaces + "|";
                }
                if (feelen < maxlen) {
                    int len = maxlen - feelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nfee = nfee + spaces + tempf + minspaces + spaces + "|";
                } else {
                    nfee = nfee + spaces + tempf + spaces + "|";
                }
                if (paidlen < maxlen) {
                    int len = maxlen - paidlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    npaid = npaid + spaces + tempp + minspaces + spaces + "|";
                } else {
                    npaid = npaid + spaces + tempp + spaces + "|";
                }
                if (dueslen < maxlen) {
                    int len = maxlen - dueslen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndues = ndues + spaces + tempd + minspaces + spaces + "|";
                } else {
                    ndues = ndues + spaces + tempd + spaces + "|";
                }
                if (datelen < maxlen) {
                    int len = maxlen - datelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndate = ndate + spaces + tempdate + minspaces + spaces + "|";
                } else {
                    ndate = ndate + spaces + tempdate + spaces + "|";
                }
                if (durationlen < maxlen) {
                    int len = maxlen - durationlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nduration = nduration + spaces + tempduration + minspaces + spaces + "|";
                } else {
                    nduration = nduration + spaces + tempduration + spaces + "|";
                }
            }
            if (course8.getSelectedItem() != "Course 8") {
                String tempc = "";
                String tempf = "";
                String tempp = "";
                String tempd = "";
                String tempdate = "";
                String tempduration = "";
                tempc = (String) course8.getSelectedItem();
                tempf = fee8.getText();
                tempp = paid8.getText();
                tempd = String.valueOf(Integer.parseInt(fee8.getText()) - Integer.parseInt(paid8.getText()));
                tempdate = d8DD.getText() + "/" + d8MM.getText() + "/" + d8YYYY.getText();
                tempduration = duration8.getText() + " " + "months";
                int courselen = tempc.length();
                int feelen = tempf.length();
                int paidlen = tempp.length();
                int dueslen = tempd.length();
                int datelen = tempdate.length();
                int durationlen = tempduration.length();
                int maxlen = Math.max(courselen, feelen);
                maxlen = Math.max(maxlen, paidlen);
                maxlen = Math.max(maxlen, dueslen);
                maxlen = Math.max(maxlen, datelen);
                maxlen = Math.max(maxlen, durationlen);
                String minspaces = "";
                if (courselen < maxlen) {
                    int len = maxlen - courselen;
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ncourses = ncourses + spaces + tempc + minspaces + spaces + "|";
                } else {
                    ncourses = ncourses + spaces + tempc + spaces + "|";
                }
                if (feelen < maxlen) {
                    int len = maxlen - feelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nfee = nfee + spaces + tempf + minspaces + spaces + "|";
                } else {
                    nfee = nfee + spaces + tempf + spaces + "|";
                }
                if (paidlen < maxlen) {
                    int len = maxlen - paidlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    npaid = npaid + spaces + tempp + minspaces + spaces + "|";
                } else {
                    npaid = npaid + spaces + tempp + spaces + "|";
                }
                if (dueslen < maxlen) {
                    int len = maxlen - dueslen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndues = ndues + spaces + tempd + minspaces + spaces + "|";
                } else {
                    ndues = ndues + spaces + tempd + spaces + "|";
                }
                if (datelen < maxlen) {
                    int len = maxlen - datelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndate = ndate + spaces + tempdate + minspaces + spaces + "|";
                } else {
                    ndate = ndate + spaces + tempdate + spaces + "|";
                }
                if (durationlen < maxlen) {
                    int len = maxlen - durationlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nduration = nduration + spaces + tempduration + minspaces + spaces + "|";
                } else {
                    nduration = nduration + spaces + tempduration + spaces + "|";
                }
            }
            if (course9.getSelectedItem() != "Course 9") {
                String tempc = "";
                String tempf = "";
                String tempp = "";
                String tempd = "";
                String tempdate = "";
                String tempduration = "";
                tempc = (String) course9.getSelectedItem();
                tempf = fee9.getText();
                tempp = paid9.getText();
                tempd = String.valueOf(Integer.parseInt(fee9.getText()) - Integer.parseInt(paid9.getText()));
                tempdate = d9DD.getText() + "/" + d9MM.getText() + "/" + d9YYYY.getText();
                tempduration = duration9.getText() + " " + "months";
                int courselen = tempc.length();
                int feelen = tempf.length();
                int paidlen = tempp.length();
                int dueslen = tempd.length();
                int datelen = tempdate.length();
                int durationlen = tempduration.length();
                int maxlen = Math.max(courselen, feelen);
                maxlen = Math.max(maxlen, paidlen);
                maxlen = Math.max(maxlen, dueslen);
                maxlen = Math.max(maxlen, datelen);
                maxlen = Math.max(maxlen, durationlen);
                String minspaces = "";
                if (courselen < maxlen) {
                    int len = maxlen - courselen;
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ncourses = ncourses + spaces + tempc + minspaces + spaces + "|";
                } else {
                    ncourses = ncourses + spaces + tempc + spaces + "|";
                }
                if (feelen < maxlen) {
                    int len = maxlen - feelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nfee = nfee + spaces + tempf + minspaces + spaces + "|";
                } else {
                    nfee = nfee + spaces + tempf + spaces + "|";
                }
                if (paidlen < maxlen) {
                    int len = maxlen - paidlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    npaid = npaid + spaces + tempp + minspaces + spaces + "|";
                } else {
                    npaid = npaid + spaces + tempp + spaces + "|";
                }
                if (dueslen < maxlen) {
                    int len = maxlen - dueslen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndues = ndues + spaces + tempd + minspaces + spaces + "|";
                } else {
                    ndues = ndues + spaces + tempd + spaces + "|";
                }
                if (datelen < maxlen) {
                    int len = maxlen - datelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndate = ndate + spaces + tempdate + minspaces + spaces + "|";
                } else {
                    ndate = ndate + spaces + tempdate + spaces + "|";
                }
                if (durationlen < maxlen) {
                    int len = maxlen - durationlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nduration = nduration + spaces + tempduration + minspaces + spaces + "|";
                } else {
                    nduration = nduration + spaces + tempduration + spaces + "|";
                }
            }
            if (course10.getSelectedItem() != "Course 10") {
                String tempc = "";
                String tempf = "";
                String tempp = "";
                String tempd = "";
                String tempdate = "";
                String tempduration = "";
                tempc = (String) course10.getSelectedItem();
                tempf = fee10.getText();
                tempp = paid10.getText();
                tempd = String.valueOf(Integer.parseInt(fee10.getText()) - Integer.parseInt(paid10.getText()));
                tempdate = d10DD.getText() + "/" + d10MM.getText() + "/" + d10YYYY.getText();
                tempduration = duration10.getText() + " " + "months";
                int courselen = tempc.length();
                int feelen = tempf.length();
                int paidlen = tempp.length();
                int dueslen = tempd.length();
                int datelen = tempdate.length();
                int durationlen = tempduration.length();
                int maxlen = Math.max(courselen, feelen);
                maxlen = Math.max(maxlen, paidlen);
                maxlen = Math.max(maxlen, dueslen);
                maxlen = Math.max(maxlen, datelen);
                maxlen = Math.max(maxlen, durationlen);
                String minspaces = "";
                if (courselen < maxlen) {
                    int len = maxlen - courselen;
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ncourses = ncourses + spaces + tempc + minspaces + spaces + "|";
                } else {
                    ncourses = ncourses + spaces + tempc + spaces + "|";
                }
                if (feelen < maxlen) {
                    int len = maxlen - feelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nfee = nfee + spaces + tempf + minspaces + spaces + "|";
                } else {
                    nfee = nfee + spaces + tempf + spaces + "|";
                }
                if (paidlen < maxlen) {
                    int len = maxlen - paidlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    npaid = npaid + spaces + tempp + minspaces + spaces + "|";
                } else {
                    npaid = npaid + spaces + tempp + spaces + "|";
                }
                if (dueslen < maxlen) {
                    int len = maxlen - dueslen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndues = ndues + spaces + tempd + minspaces + spaces + "|";
                } else {
                    ndues = ndues + spaces + tempd + spaces + "|";
                }
                if (datelen < maxlen) {
                    int len = maxlen - datelen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    ndate = ndate + spaces + tempdate + minspaces + spaces + "|";
                } else {
                    ndate = ndate + spaces + tempdate + spaces + "|";
                }
                if (durationlen < maxlen) {
                    int len = maxlen - durationlen;
                    minspaces = "";
                    for (int z = 0; z < len; z++) {
                        minspaces += " ";
                    }
                    nduration = nduration + spaces + tempduration + minspaces + spaces + "|";
                } else {
                    nduration = nduration + spaces + tempduration + spaces + "|";
                }
            }

            additionalcourse.this.hide();
        }

    }//GEN-LAST:event_kButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additionalcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additionalcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additionalcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additionalcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additionalcourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> course10;
    private javax.swing.JComboBox<String> course6;
    private javax.swing.JComboBox<String> course7;
    private javax.swing.JComboBox<String> course8;
    private javax.swing.JComboBox<String> course9;
    private javax.swing.JTextField d10DD;
    private javax.swing.JTextField d10MM;
    private javax.swing.JTextField d10YYYY;
    private javax.swing.JTextField d6DD;
    private javax.swing.JTextField d6MM;
    private javax.swing.JTextField d6YYYY;
    private javax.swing.JTextField d7DD;
    private javax.swing.JTextField d7MM;
    private javax.swing.JTextField d7YYYY;
    private javax.swing.JTextField d8DD;
    private javax.swing.JTextField d8MM;
    private javax.swing.JTextField d8YYYY;
    private javax.swing.JTextField d9DD;
    private javax.swing.JTextField d9MM;
    private javax.swing.JTextField d9YYYY;
    private javax.swing.JLabel dateerr;
    private javax.swing.JTextField duration10;
    private javax.swing.JTextField duration6;
    private javax.swing.JTextField duration7;
    private javax.swing.JTextField duration8;
    private javax.swing.JTextField duration9;
    private javax.swing.JLabel durationerr;
    private javax.swing.JTextField fee10;
    private javax.swing.JTextField fee6;
    private javax.swing.JTextField fee7;
    private javax.swing.JTextField fee8;
    private javax.swing.JTextField fee9;
    private javax.swing.JLabel feeerr;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JTextField paid10;
    private javax.swing.JTextField paid6;
    private javax.swing.JTextField paid7;
    private javax.swing.JTextField paid8;
    private javax.swing.JTextField paid9;
    private javax.swing.JLabel paiderr;
    // End of variables declaration//GEN-END:variables
}
