/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class datesearch extends javax.swing.JFrame {

    /**
     * Creates new form datesearch
     */
    public datesearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        srclbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        DD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        MM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        YYYY = new javax.swing.JTextField();
        kButton3 = new com.k33ptoo.components.KButton();
        closebutt = new com.k33ptoo.components.KButton();

        setTitle("Search by Date");

        jPanel3.setBackground(new java.awt.Color(2, 45, 145));
        jPanel3.setPreferredSize(new java.awt.Dimension(1330, 635));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Enter Date of Admission : ");

        srclbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtarea.setRows(5);
        jScrollPane2.setViewportView(txtarea);

        DD.setBackground(new Color (0,0,0,0));
        DD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        DD.setOpaque(false);
        DD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DDKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText(" /");

        MM.setBackground(new Color (0,0,0,0));
        MM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MM.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        MM.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText(" /");

        YYYY.setBackground(new Color (0,0,0,0));
        YYYY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        YYYY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        YYYY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        YYYY.setOpaque(false);
        YYYY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YYYYActionPerformed(evt);
            }
        });
        YYYY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YYYYKeyPressed(evt);
            }
        });

        kButton3.setBorder(null);
        kButton3.setText("Search");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(2, 45, 145));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(102, 102, 255));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        closebutt.setBorder(null);
        closebutt.setText("Close");
        closebutt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        closebutt.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        closebutt.setkEndColor(new java.awt.Color(255, 51, 51));
        closebutt.setkFillButton(false);
        closebutt.setkForeGround(new java.awt.Color(255, 102, 102));
        closebutt.setkHoverForeGround(new java.awt.Color(255, 51, 51));
        closebutt.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        closebutt.setkStartColor(new java.awt.Color(204, 0, 0));
        closebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(379, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(5, 5, 5)
                        .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed

        int check = 0;
        int match = 0;

        try {
            if (Integer.parseInt(DD.getText()) > 0 && Integer.parseInt(DD.getText()) <= 31 && Integer.parseInt(MM.getText()) > 0 && Integer.parseInt(MM.getText()) <= 12 && YYYY.getText().length() == 4) {

            } else {
                check = 1;
                match = 1;
                srclbl.setForeground(Color.red);
                srclbl.setText("Wrong date, try again ");
            }
        } catch (NumberFormatException e) {
            check = 1;
            match = 1;
            srclbl.setForeground(Color.red);
            srclbl.setText("Wrong date, try again ");
        }

        if (check == 0) {
            txtarea.setText("\n");
            String datestr = DD.getText() + "/" + MM.getText() + "/" + YYYY.getText();
            String dateR = "";
            for (int i = 0; i < students.a; i++) {
                for (int j = 0; j < students.dateofaddmission[i].length(); j++) {
                    if (students.dateofaddmission[i].charAt(j) == ' ' || students.dateofaddmission[i].charAt(j) == '|') {
                        //JOptionPane.showMessageDialog(null, "dateR : " + dateR + "datestr : " + datestr );
                        if (Objects.equals(dateR, datestr)) {
                            srclbl.setForeground(Color.green);
                            srclbl.setText("Match Found");
                            txtarea.append("  Name              : " + students.name[i] + "\n"
                                    + ("  Father's Name     : " + students.fname[i] + "\n")
                                    + ("  Registration No.  : " + students.roll[i] + "\n")
                                    + ("  Contact No.       : " + students.phno[i] + "\n")
                                    + ("  DOB               : " + students.dob[i] + "\n")
                                    + ("  Gender            : " + students.gender[i] + "\n")
                                    + ("  Category          : " + students.category[i] + "\n")
                                    + ("  Address           : " + students.address[i] + "\n")
                                    + ("  Courses           : " + students.course[i] + "\n")
                                    + ("  Course Fee        : " + students.fee[i] + "\n")
                                    + ("  Fee Paid          : " + students.paid[i] + "\n")
                                    + ("  Fee Dues          : " + students.dues[i] + "\n")
                                    + ("  Date of Admission : " + students.dateofaddmission[i] + "\n")
                                    + "  Course Duration   : " + students.duration[i] + "\n"
                                    + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                                    + "\n");
                            match = 1;
                            j = students.dateofaddmission[i].length();
                        }
                        dateR = "";
                    } else {
                        dateR += students.dateofaddmission[i].charAt(j);
                    }

                }
            }

        }

        if (match == 0) {
            srclbl.setForeground(Color.red);;
            srclbl.setText("No Students found on this date");
        }


    }//GEN-LAST:event_kButton3ActionPerformed

    private void YYYYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YYYYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YYYYActionPerformed

    private void closebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttActionPerformed
       datesearch.this.hide();
    }//GEN-LAST:event_closebuttActionPerformed

    private void YYYYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YYYYKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            int check = 0;
            int match = 0;

            try {
                if (Integer.parseInt(DD.getText()) > 0 && Integer.parseInt(DD.getText()) <= 31 && Integer.parseInt(MM.getText()) > 0 && Integer.parseInt(MM.getText()) <= 12 && YYYY.getText().length() == 4) {

                } else {
                    check = 1;
                    match = 1;
                    srclbl.setForeground(Color.red);
                    srclbl.setText("Wrong date, try again ");
                }
            } catch (NumberFormatException e) {
                check = 1;
                match = 1;
                srclbl.setForeground(Color.red);
                srclbl.setText("Wrong date, try again ");
            }

            if (check == 0) {
                txtarea.setText("\n");
                String datestr = DD.getText() + "/" + MM.getText() + "/" + YYYY.getText();
                String dateR = "";
                for (int i = 0; i < students.a; i++) {
                    for (int j = 0; j < students.dateofaddmission[i].length(); j++) {
                        if (students.dateofaddmission[i].charAt(j) == ' ' || students.dateofaddmission[i].charAt(j) == '|') {
                            //JOptionPane.showMessageDialog(null, "dateR : " + dateR + "datestr : " + datestr );
                            if (Objects.equals(dateR, datestr)) {
                                srclbl.setForeground(Color.green);
                                srclbl.setText("Match Found");
                                txtarea.append("  Name              : " + students.name[i] + "\n"
                                        + ("  Father's Name     : " + students.fname[i] + "\n")
                                        + ("  Registration No.  : " + students.roll[i] + "\n")
                                        + ("  Contact No.       : " + students.phno[i] + "\n")
                                        + ("  DOB               : " + students.dob[i] + "\n")
                                        + ("  Gender            : " + students.gender[i] + "\n")
                                        + ("  Category          : " + students.category[i] + "\n")
                                        + ("  Address           : " + students.address[i] + "\n")
                                        + ("  Courses           : " + students.course[i] + "\n")
                                        + ("  Course Fee        : " + students.fee[i] + "\n")
                                        + ("  Fee Paid          : " + students.paid[i] + "\n")
                                        + ("  Fee Dues          : " + students.dues[i] + "\n")
                                        + ("  Date of Admission : " + students.dateofaddmission[i] + "\n")
                                        + "  Course Duration   : " + students.duration[i] + "\n"
                                        + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                                        + "\n");
                                match = 1;
                                j = students.dateofaddmission[i].length();
                            }
                            dateR = "";
                        } else {
                            dateR += students.dateofaddmission[i].charAt(j);
                        }

                    }
                }

            }

            if (match == 0) {
                srclbl.setForeground(Color.red);;
                srclbl.setText("No Students found on this date");
            }
        }
    }//GEN-LAST:event_YYYYKeyPressed

    private void DDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DDKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            datesearch.this.hide();
        }
    }//GEN-LAST:event_DDKeyPressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datesearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DD;
    private javax.swing.JTextField MM;
    private javax.swing.JTextField YYYY;
    private com.k33ptoo.components.KButton closebutt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KButton kButton3;
    public static javax.swing.JLabel srclbl;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
