/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Objects;

/**
 *
 * @author shubh
 */
public class deleteentry extends javax.swing.JFrame {

    /**
     * Creates new form deleteentry
     */
    static int roll;
    static int check = 0;

    public deleteentry() {
        initComponents();
        myinitComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rolllinp = new javax.swing.JTextField();
        nobutt = new com.k33ptoo.components.KButton();
        warninglbl = new javax.swing.JLabel();
        kButton3 = new com.k33ptoo.components.KButton();
        yesbutt = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Delete entry");
        setMinimumSize(new java.awt.Dimension(640, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 45, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl2.setForeground(new java.awt.Color(204, 0, 0));
        lbl2.setText("Are you sure ?");
        jPanel2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 80, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setText("Enter Registration No. :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        rolllinp.setBackground(new Color(0,0,0,0));
        rolllinp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rolllinp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        rolllinp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rolllinp.setOpaque(false);
        rolllinp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolllinpActionPerformed(evt);
            }
        });
        rolllinp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rolllinpKeyPressed(evt);
            }
        });
        jPanel2.add(rolllinp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 290, -1));

        nobutt.setBorder(null);
        nobutt.setText("No");
        nobutt.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        nobutt.setkEndColor(new java.awt.Color(255, 255, 255));
        nobutt.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        nobutt.setkHoverForeGround(new java.awt.Color(0, 153, 0));
        nobutt.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        nobutt.setkStartColor(new java.awt.Color(0, 153, 0));
        nobutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobuttActionPerformed(evt);
            }
        });
        jPanel2.add(nobutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 60, 20));

        warninglbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        warninglbl.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(warninglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 220, 30));

        kButton3.setBorder(null);
        kButton3.setText("Drop");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(255, 204, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton3.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton3.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, 30));

        yesbutt.setBorder(null);
        yesbutt.setText("Yes");
        yesbutt.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        yesbutt.setkEndColor(new java.awt.Color(255, 204, 204));
        yesbutt.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        yesbutt.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        yesbutt.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        yesbutt.setkStartColor(new java.awt.Color(255, 0, 0));
        yesbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesbuttActionPerformed(evt);
            }
        });
        jPanel2.add(yesbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Warning : You are deleating an Input");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 220, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 710, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myinitComponents() {
        check = 0;
        warninglbl.setText("");
        lbl2.setVisible(false);
        yesbutt.setVisible(false);
        nobutt.setVisible(false);
    }

    private void rolllinpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolllinpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolllinpActionPerformed

    private void nobuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobuttActionPerformed
        deleteentry.this.hide();
    }//GEN-LAST:event_nobuttActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed

        myinitComponents();

        String rollstr = rolllinp.getText();
        int i;
        for (i = 0; i < students.a; i++) {
            if (Objects.equals(rollstr, students.roll[i])) {
                roll = i;
                warninglbl.setText(students.name[i] + "'s  details will be deleated.");
                break;
            }

        }
        if (i == students.a) {
            check = 1;
            warninglbl.setText("Reg No. did't match to our database");
        }

        if (check == 0) {
            warninglbl.setText("");
            lbl2.setVisible(true);
            yesbutt.setVisible(true);
            nobutt.setVisible(true);
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void yesbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesbuttActionPerformed

        for (int i = roll + 1; i < students.a; i++) {
            students.name[i - 1] = students.name[i];
            students.fname[i - 1] = students.fname[i];
            students.roll[i - 1] = students.roll[i];
            students.phno[i - 1] = students.phno[i];
            students.dob[i - 1] = students.dob[i];
            students.gender[i - 1] = students.gender[i];
            students.category[i - 1] = students.category[i];
            students.address[i - 1] = students.address[i];
            students.course[i - 1] = students.course[i];
            students.fee[i - 1] = students.fee[i];
            students.paid[i - 1] = students.paid[i];
            students.dues[i - 1] = students.dues[i];
            students.dateofaddmission[i - 1] = students.dateofaddmission[i];
            students.duration[i - 1] = students.duration[i];
        }
        students.a--;
        students.saveData();
        students.save_sz_data();
        warninglbl.setText("        Info Deleated successfully");
    }//GEN-LAST:event_yesbuttActionPerformed

    private void rolllinpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rolllinpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            deleteentry.this.hide();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            myinitComponents();

            String rollstr = rolllinp.getText();
            int i;
            for (i = 0; i < students.a; i++) {
                if (Objects.equals(rollstr, students.roll[i])) {
                    roll = i;
                    warninglbl.setText(students.name[i] + "'s  details will be deleated.");
                    break;
                }

            }
            if (i == students.a) {
                check = 1;
                warninglbl.setText("Reg No. did't match to our database");
            }

            if (check == 0) {
                warninglbl.setText("");
                lbl2.setVisible(true);
                yesbutt.setVisible(true);
                nobutt.setVisible(true);
            }
        }
    }//GEN-LAST:event_rolllinpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteentry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JLabel lbl2;
    private com.k33ptoo.components.KButton nobutt;
    public static javax.swing.JTextField rolllinp;
    private javax.swing.JLabel warninglbl;
    private com.k33ptoo.components.KButton yesbutt;
    // End of variables declaration//GEN-END:variables
}
