/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author shubh
 */
public class fathersearch extends javax.swing.JFrame {

    /**
     * Creates new form fathersearch
     */
    public fathersearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        srclbl = new javax.swing.JLabel();
        nameinp = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        namesearch1 = new com.shujava.ikon_dtabs_gui_netbeans.namesearch();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        srclbl1 = new javax.swing.JLabel();
        fnameinp = new javax.swing.JTextField();
        kButton2 = new com.k33ptoo.components.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea1 = new javax.swing.JTextArea();
        closebutt3 = new com.k33ptoo.components.KButton();

        jFrame1.setTitle("Search by Student's Name");
        jFrame1.setMinimumSize(new java.awt.Dimension(1310, 660));
        jFrame1.setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(2, 45, 145));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Enter Name  : ");

        srclbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        nameinp.setBackground(new Color(0,0,0,0));
        nameinp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameinp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nameinp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nameinp.setOpaque(false);
        nameinp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameinpActionPerformed(evt);
            }
        });

        kButton1.setBorder(null);
        kButton1.setText("Search");
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(2, 45, 145));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(102, 102, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameinp, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addComponent(srclbl, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameinp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setTitle("Search by Student's Father's name");
        setMinimumSize(new java.awt.Dimension(1310, 660));
        setPreferredSize(new java.awt.Dimension(1310, 660));

        jPanel3.setBackground(new java.awt.Color(2, 45, 145));
        jPanel3.setPreferredSize(new java.awt.Dimension(1330, 635));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Enter Father's Name  : ");

        srclbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        fnameinp.setBackground(new Color(0,0,0,0));
        fnameinp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnameinp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        fnameinp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        fnameinp.setOpaque(false);
        fnameinp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameinpActionPerformed(evt);
            }
        });
        fnameinp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fnameinpKeyPressed(evt);
            }
        });

        kButton2.setBorder(null);
        kButton2.setText("Search");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton2.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(2, 45, 145));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(102, 102, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        txtarea1.setColumns(20);
        txtarea1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtarea1.setRows(5);
        jScrollPane2.setViewportView(txtarea1);

        closebutt3.setBorder(null);
        closebutt3.setText("Close");
        closebutt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closebutt3.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        closebutt3.setkEndColor(new java.awt.Color(255, 51, 51));
        closebutt3.setkFillButton(false);
        closebutt3.setkForeGround(new java.awt.Color(255, 102, 102));
        closebutt3.setkHoverForeGround(new java.awt.Color(255, 51, 51));
        closebutt3.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        closebutt3.setkStartColor(new java.awt.Color(204, 0, 0));
        closebutt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebutt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closebutt3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fnameinp, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(srclbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2)))
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fnameinp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(srclbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(closebutt3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameinpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameinpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameinpActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        String fnametemp = fnameinp.getText();
        int[] match = new int[students.a];
        txtarea.setText("\n");
        for (int k = 0; k < students.a; k++) {
            for (int j = 0; j < Math.min(students.fname[k].length(), fnametemp.length()); j++) {
                // j < fnametemp.length() gives error (out of bounds) bcz input can be greater than name[k].length().
                if (students.fname[k].length() < fnametemp.length()) {
                    break;
                }
                if (fnametemp.charAt(j) == students.fname[k].charAt(j)) {
                    match[k] = 1;
                } else {
                    match[k] = 0;
                    break;
                }
            }
        }
        for (int j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                srclbl.setForeground(Color.green);
                srclbl.setText("Match Found");
                txtarea.append("  Name              : " + students.name[j] + "\n"
                        + ("  Fathers Name      : " + students.fname[j] + "\n")
                        + ("  Registration No.  : " + students.roll[j] + "\n")
                        + ("  Contact No.       : " + students.phno[j] + "\n")
                        + ("  DOB               : " + students.dob[j] + "\n")
                        + ("  Gender            : " + students.gender[j] + "\n")
                        + ("  Category          : " + students.category[j] + "\n")
                        + ("  Address           : " + students.address[j] + "\n")
                        + ("  Courses           : " + students.course[j] + "\n")
                        + ("  Course Fee        : " + students.fee[j] + "\n")
                        + ("  Fee Paid          : " + students.paid[j] + "\n")
                        + ("  Fee Dues          : " + students.dues[j] + "\n")
                        + ("  Date of Admission : " + students.dateofaddmission[j] + "\n")
                        + "  Course Duration   : " + students.duration[j] + "\n"
                        + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                        + "\n");
            }
        }
        int j;
        for (j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                break;
            }
        }
        if (j == match.length) {
            srclbl.setForeground(Color.red);
            srclbl.setText("Father's name ['" + fnametemp + "'] didn't match to our database");
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void fnameinpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameinpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameinpActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        String fnametemp = fnameinp.getText();
        int[] match = new int[students.a];
        txtarea1.setText("\n");
        for (int k = 0; k < students.a; k++) {
            for (int j = 0; j < Math.min(students.fname[k].length(), fnametemp.length()); j++) {
                // j < fnametemp.length() gives error (out of bounds) bcz input can be greater than name[k].length().
                if (students.fname[k].length() < fnametemp.length()) {
                    break;
                }
                if (fnametemp.charAt(j) == students.fname[k].charAt(j)) {
                    match[k] = 1;
                } else {
                    match[k] = 0;
                    break;
                }
            }
        }
        for (int j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                srclbl1.setForeground(Color.green);
                srclbl1.setText("Match Found");
                txtarea1.append("  Name              : " + students.name[j] + "\n"
                        + ("  Father's Name     : " + students.fname[j] + "\n")
                        + ("  Registration No.  : " + students.roll[j] + "\n")
                        + ("  Contact No.       : " + students.phno[j] + "\n")
                        + ("  DOB               : " + students.dob[j] + "\n")
                        + ("  Gender            : " + students.gender[j] + "\n")
                        + ("  Category          : " + students.category[j] + "\n")
                        + ("  Address           : " + students.address[j] + "\n")
                        + ("  Courses           : " + students.course[j] + "\n")
                        + ("  Course Fee        : " + students.fee[j] + "\n")
                        + ("  Fee Paid          : " + students.paid[j] + "\n")
                        + ("  Fee Dues          : " + students.dues[j] + "\n")
                        + ("  Date of Admission : " + students.dateofaddmission[j] + "\n")
                        + "  Course Duration   : " + students.duration[j] + "\n"
                        + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                        + "\n");
            }
        }
        int j;
        for (j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                break;
            }
        }
        if (j == match.length) {
            srclbl1.setForeground(Color.red);
            srclbl1.setText("Father's name ['" + fnametemp + "'] didn't match to our database");
        }

    }//GEN-LAST:event_kButton2ActionPerformed

    private void closebutt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebutt3ActionPerformed
        fathersearch.this.hide();
    }//GEN-LAST:event_closebutt3ActionPerformed

    private void fnameinpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameinpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            fathersearch.this.hide();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String fnametemp = fnameinp.getText();
            int[] match = new int[students.a];
            txtarea1.setText("\n");
            for (int k = 0; k < students.a; k++) {
                for (int j = 0; j < Math.min(students.fname[k].length(), fnametemp.length()); j++) {
                    // j < fnametemp.length() gives error (out of bounds) bcz input can be greater than name[k].length().
                    if (students.fname[k].length() < fnametemp.length()) {
                        break;
                    }
                    if (fnametemp.charAt(j) == students.fname[k].charAt(j)) {
                        match[k] = 1;
                    } else {
                        match[k] = 0;
                        break;
                    }
                }
            }
            for (int j = 0; j < match.length; j++) {
                if (match[j] == 1) {
                    srclbl1.setForeground(Color.green);
                    srclbl1.setText("Match Found");
                    txtarea1.append("  Name              : " + students.name[j] + "\n"
                            + ("  Father's Name     : " + students.fname[j] + "\n")
                            + ("  Registration No.  : " + students.roll[j] + "\n")
                            + ("  Contact No.       : " + students.phno[j] + "\n")
                            + ("  DOB               : " + students.dob[j] + "\n")
                            + ("  Gender            : " + students.gender[j] + "\n")
                            + ("  Category          : " + students.category[j] + "\n")
                            + ("  Address           : " + students.address[j] + "\n")
                            + ("  Courses           : " + students.course[j] + "\n")
                            + ("  Course Fee        : " + students.fee[j] + "\n")
                            + ("  Fee Paid          : " + students.paid[j] + "\n")
                            + ("  Fee Dues          : " + students.dues[j] + "\n")
                            + ("  Date of Admission : " + students.dateofaddmission[j] + "\n")
                            + "  Course Duration   : " + students.duration[j] + "\n"
                            + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                            + "\n");
                }
            }
            int j;
            for (j = 0; j < match.length; j++) {
                if (match[j] == 1) {
                    break;
                }
            }
            if (j == match.length) {
                srclbl1.setForeground(Color.red);
                srclbl1.setText("Father's name ['" + fnametemp + "'] didn't match to our database");
            }
        }
    }//GEN-LAST:event_fnameinpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fathersearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fathersearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fathersearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fathersearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fathersearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton closebutt3;
    public static javax.swing.JTextField fnameinp;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    public static javax.swing.JTextField nameinp;
    private com.shujava.ikon_dtabs_gui_netbeans.namesearch namesearch1;
    public static javax.swing.JLabel srclbl;
    public static javax.swing.JLabel srclbl1;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextArea txtarea1;
    // End of variables declaration//GEN-END:variables
}
