/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author shubh
 */
public class namesearch extends javax.swing.JFrame {

    private static void setPrefHeight(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form namesearch
     */
    public namesearch() {
        initComponents();
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        srclbl = new javax.swing.JLabel();
        nameinp = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        closebutt = new com.k33ptoo.components.KButton();

        setTitle("Search by Student's Name");
        setMinimumSize(new java.awt.Dimension(1200, 500));
        setPreferredSize(new java.awt.Dimension(1330, 670));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(2, 45, 145));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Enter Name  : ");

        srclbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        nameinp.setBackground(new Color(0,0,0,0));
        nameinp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameinp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameinp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nameinp.setOpaque(false);
        nameinp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameinpActionPerformed(evt);
            }
        });
        nameinp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameinpKeyPressed(evt);
            }
        });

        kButton1.setBorder(null);
        kButton1.setText("Search");
        kButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(102, 204, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(2, 45, 145));
        kButton1.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton1.setkStartColor(new java.awt.Color(102, 102, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtarea.setRows(5);
        jScrollPane1.setViewportView(txtarea);

        closebutt.setBorder(null);
        closebutt.setText("Close");
        closebutt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        closebutt.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        closebutt.setkEndColor(new java.awt.Color(255, 51, 51));
        closebutt.setkFillButton(false);
        closebutt.setkForeGround(new java.awt.Color(255, 102, 102));
        closebutt.setkHoverForeGround(new java.awt.Color(255, 51, 51));
        closebutt.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        closebutt.setkStartColor(new java.awt.Color(204, 0, 0));
        closebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameinp, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(srclbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1214, 1214, 1214)
                        .addComponent(closebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(nameinp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(srclbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(closebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myinitComponents() {

    }
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        reset();

        String nametemp = nameinp.getText();
        int[] match = new int[students.a];
        txtarea.setText("\n");
        for (int k = 0; k < students.a; k++) {
            for (int j = 0; j < Math.min(students.name[k].length(), nametemp.length()); j++) {
                // j < nametemp.length() gives error (out of bounds) bcz input can be greater than name[k].length().
                if (students.name[k].length() < nametemp.length()) {
                    break;
                }
                if (nametemp.charAt(j) == students.name[k].charAt(j)) {
                    match[k] = 1;
                } else {
                    match[k] = 0;
                    break;
                }
            }
        }
        for (int j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                srclbl.setForeground(Color.green);
                srclbl.setText("Match Found");
                txtarea.append("  Name              : " + students.name[j] + "\n"
                        + ("  Father's Name     : " + students.fname[j] + "\n")
                        + ("  Registration No.  : " + students.roll[j] + "\n")
                        + ("  Contact No.       : " + students.phno[j] + "\n")
                        + ("  DOB               : " + students.dob[j] + "\n")
                        + ("  Gender            : " + students.gender[j] + "\n")
                        + ("  Category          : " + students.category[j] + "\n")
                        + ("  Address           : " + students.address[j] + "\n")
                        + ("  Courses           : " + students.course[j] + "\n")
                        + ("  Course Fee        : " + students.fee[j] + "\n")
                        + ("  Fee Paid          : " + students.paid[j] + "\n")
                        + ("  Fee Dues          : " + students.dues[j] + "\n")
                        + ("  Date of Admission : " + students.dateofaddmission[j] + "\n")
                        + "  Course Duration   : " + students.duration[j] + "\n"
                        + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                        + "\n");
            }
        }
        int j;
        for (j = 0; j < match.length; j++) {
            if (match[j] == 1) {
                break;
            }
        }
        if (j == match.length) {
            srclbl.setForeground(Color.red);
            srclbl.setText("Name ['" + nametemp + "'] didn't match to our database");
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void nameinpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameinpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameinpActionPerformed

    private void closebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttActionPerformed
        namesearch.this.hide();
    }//GEN-LAST:event_closebuttActionPerformed

    private void nameinpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameinpKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            namesearch.this.hide();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            reset();

            String nametemp = nameinp.getText();
            int[] match = new int[students.a];
            txtarea.setText("\n");
            for (int k = 0; k < students.a; k++) {
                for (int j = 0; j < Math.min(students.name[k].length(), nametemp.length()); j++) {
                    // j < nametemp.length() gives error (out of bounds) bcz input can be greater than name[k].length().
                    if (students.name[k].length() < nametemp.length()) {
                        break;
                    }
                    if (nametemp.charAt(j) == students.name[k].charAt(j)) {
                        match[k] = 1;
                    } else {
                        match[k] = 0;
                        break;
                    }
                }
            }
            for (int j = 0; j < match.length; j++) {
                if (match[j] == 1) {
                    srclbl.setForeground(Color.green);
                    srclbl.setText("Match Found");
                    txtarea.append("  Name              : " + students.name[j] + "\n"
                            + ("  Father's Name     : " + students.fname[j] + "\n")
                            + ("  Registration No.  : " + students.roll[j] + "\n")
                            + ("  Contact No.       : " + students.phno[j] + "\n")
                            + ("  DOB               : " + students.dob[j] + "\n")
                            + ("  Gender            : " + students.gender[j] + "\n")
                            + ("  Category          : " + students.category[j] + "\n")
                            + ("  Address           : " + students.address[j] + "\n")
                            + ("  Courses           : " + students.course[j] + "\n")
                            + ("  Course Fee        : " + students.fee[j] + "\n")
                            + ("  Fee Paid          : " + students.paid[j] + "\n")
                            + ("  Fee Dues          : " + students.dues[j] + "\n")
                            + ("  Date of Admission : " + students.dateofaddmission[j] + "\n")
                            + "  Course Duration   : " + students.duration[j] + "\n"
                            + "  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------"
                            + "\n");
                }
            }
            int j;
            for (j = 0; j < match.length; j++) {
                if (match[j] == 1) {
                    break;
                }
            }
            if (j == match.length) {
                srclbl.setForeground(Color.red);
                srclbl.setText("Name ['" + nametemp + "'] didn't match to our database");
            }
        }
    }//GEN-LAST:event_nameinpKeyPressed

    private void reset() {
        srclbl.setForeground(Color.black);
        srclbl.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(namesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(namesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(namesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(namesearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new namesearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton closebutt;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton1;
    public static javax.swing.JTextField nameinp;
    public static javax.swing.JLabel srclbl;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
