package com.shujava.ikon_dtabs_gui_netbeans;
//import com.shujava.ikon_dtabs_gui_netbeans.optionsfrm.progress;

import com.k33ptoo.components.KButton;
import static com.shujava.ikon_dtabs_gui_netbeans.optionsfrm.main;
import static com.shujava.ikon_dtabs_gui_netbeans.students.a;
import static com.shujava.ikon_dtabs_gui_netbeans.students.addressnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.categorynew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.coursenew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.dateofaddnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.dobnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.duesnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.durationnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.feenew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.fnamenew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.gendernew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.namenew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.paidnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.phnonew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.rollnew;
import static com.shujava.ikon_dtabs_gui_netbeans.students.size_of_dta;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import keeptoo.KGradientPanel;

/**
 *
 * @author shubh
 */
public final class optionsfrm extends javax.swing.JFrame {

    pbThread t1;

    public optionsfrm() {
        initComponents();
        modifyinitComponents();
        showtime();
        showdate();
        t1 = new pbThread(loading);
        t1.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        newstu = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        kButton9 = new com.k33ptoo.components.KButton();
        kButton10 = new com.k33ptoo.components.KButton();
        kButton11 = new com.k33ptoo.components.KButton();
        kButton12 = new com.k33ptoo.components.KButton();
        kButton13 = new com.k33ptoo.components.KButton();
        loading = new javax.swing.JProgressBar();
        loadinglbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datebutt = new com.k33ptoo.components.KButton();
        timelbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ikon Database v2.1.0");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 130));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 54, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_student_registration_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 30, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_search_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_search_client_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 50, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_guardian_26px.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 30, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_search_range_26px.png"))); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 30, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_time_24px_1.png"))); // NOI18N
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 30, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_edit_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 50, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_delete_trash_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_dues_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 50, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_pay_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 40, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_time_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 40, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_course_24px.png"))); // NOI18N
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 30, 40));

        kButton2.setBorder(null);
        kButton2.setText("       Search by Name");
        kButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton2.setkAllowGradient(false);
        kButton2.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 210, 40));

        newstu.setBorder(null);
        newstu.setText("New Student");
        newstu.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        newstu.setkAllowGradient(false);
        newstu.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        newstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newstuActionPerformed(evt);
            }
        });
        kGradientPanel1.add(newstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 220, 40));

        kButton4.setBorder(null);
        kButton4.setText("         Search by Reg No.");
        kButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton4.setkAllowGradient(false);
        kButton4.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 220, 40));

        kButton5.setBorder(null);
        kButton5.setText("            Search by Fathers Name");
        kButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        kButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kButton5.setkAllowGradient(false);
        kButton5.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 220, 40));

        kButton6.setBorder(null);
        kButton6.setText("     Search in Range");
        kButton6.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton6.setkAllowGradient(false);
        kButton6.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 220, 40));

        kButton7.setBorder(null);
        kButton7.setText("      Search by Date");
        kButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton7.setkAllowGradient(false);
        kButton7.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 210, 40));

        kButton8.setBorder(null);
        kButton8.setText("Pay Dues");
        kButton8.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton8.setkAllowGradient(false);
        kButton8.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 220, 40));

        kButton9.setBorder(null);
        kButton9.setText("        Show Outdated Students");
        kButton9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        kButton9.setkAllowGradient(false);
        kButton9.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 220, 40));

        kButton10.setBorder(null);
        kButton10.setText("Add Course");
        kButton10.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton10.setkAllowGradient(false);
        kButton10.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 210, 40));

        kButton11.setBorder(null);
        kButton11.setText("Edit Entry");
        kButton11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton11.setkAllowGradient(false);
        kButton11.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 220, 40));

        kButton12.setBorder(null);
        kButton12.setText("Delete Entry");
        kButton12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton12.setkAllowGradient(false);
        kButton12.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 220, 40));

        kButton13.setBorder(null);
        kButton13.setText("Show Dues");
        kButton13.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        kButton13.setkAllowGradient(false);
        kButton13.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 210, 40));

        loading.setStringPainted(true);
        kGradientPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 190, 20));

        loadinglbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        loadinglbl.setForeground(new java.awt.Color(0, 153, 0));
        loadinglbl.setText("Loading Students data ....");
        kGradientPanel1.add(loadinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 180, 20));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/IKON LOGOs.png"))); // NOI18N
        kGradientPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 60, 20));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 810, 450));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 870, 530));

        datebutt.setBorder(null);
        datebutt.setForeground(new java.awt.Color(2, 54, 145));
        datebutt.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        datebutt.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        datebutt.setkEndColor(new java.awt.Color(255, 255, 255));
        datebutt.setkForeGround(new java.awt.Color(2, 45, 145));
        datebutt.setkHoverColor(new java.awt.Color(2, 45, 145));
        datebutt.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        datebutt.setkHoverForeGround(new java.awt.Color(2, 54, 145));
        datebutt.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        datebutt.setkPressedColor(new java.awt.Color(255, 255, 255));
        datebutt.setkStartColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(datebutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 100, 20));

        timelbl.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        timelbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Students Database Manager");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8_database_16pxnew.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyinitComponents() {
        newstu.setEnabled(false);
        kButton2.setEnabled(false);
        kButton4.setEnabled(false);
        kButton5.setEnabled(false);
        kButton6.setEnabled(false);
        kButton7.setEnabled(false);
        kButton8.setEnabled(false);
        kButton9.setEnabled(false);
        kButton10.setEnabled(false);
        kButton11.setEnabled(false);
        kButton12.setEnabled(false);
        kButton13.setEnabled(false);

    }

    private void setbuttactive() {
        newstu.setEnabled(true);
        kButton2.setEnabled(true);
        kButton4.setEnabled(true);
        kButton5.setEnabled(true);
        kButton6.setEnabled(true);
        kButton7.setEnabled(true);
        kButton8.setEnabled(true);
        kButton9.setEnabled(true);
        kButton10.setEnabled(true);
        kButton11.setEnabled(true);
        kButton12.setEnabled(true);
        kButton13.setEnabled(true);
    }

    class pbThread extends Thread {

        JProgressBar pbar;

        pbThread(JProgressBar pbar) {
            pbar = loading;
        }

        public void run() {
            int min = 0;
            int max = 50;
            loading.setMinimum(min);
            loading.setMaximum(max);
            loading.setValue(0);
            try {
                BufferedReader br = new BufferedReader(new FileReader("s_dta_0.txt"));
                BufferedReader sz_dta = new BufferedReader(new FileReader("sz_dta.txt"));
                size_of_dta = Integer.parseInt(sz_dta.readLine());
                students.a = size_of_dta;
                loading.setMaximum(0);
                loading.setMaximum(size_of_dta - 1);
                for (int i = 0; i < students.a; i++) {
                    namenew = br.readLine();
                    fnamenew = br.readLine();
                    rollnew = br.readLine();
                    phnonew = br.readLine();
                    dobnew = br.readLine();
                    gendernew = br.readLine();
                    categorynew = br.readLine();
                    addressnew = br.readLine();
                    students.ispassnew = Boolean.parseBoolean(br.readLine());
                    coursenew = br.readLine();
                    feenew = br.readLine();
                    paidnew = br.readLine();
                    duesnew = br.readLine();
                    dateofaddnew = br.readLine();
                    durationnew = br.readLine();
                    students.name[i] = namenew;
                    students.fname[i] = fnamenew;
                    students.roll[i] = rollnew;
                    students.phno[i] = phnonew;
                    students.dob[i] = dobnew;
                    students.gender[i] = gendernew;
                    students.category[i] = categorynew;
                    students.address[i] = addressnew;
                    students.ispass[i] = students.ispassnew;
                    students.course[i] = coursenew;
                    students.fee[i] = feenew;
                    students.paid[i] = paidnew;
                    students.dues[i] = duesnew;
                    students.dateofaddmission[i] = dateofaddnew;
                    students.duration[i] = durationnew;

                    loading.setValue(i);

                    for (int j = 0; j < 3; j++) {
                        loadinglbl.setText("Loading " + namenew + "'s details");
                        Thread.sleep(5);
                        loadinglbl.setText("Loading " + namenew + "'s details ..");
                        Thread.sleep(5);
                        loadinglbl.setText("Loading " + namenew + "'s details ....");
                        Thread.sleep(5);
                        loadinglbl.setText("Loading " + namenew + "'s details ........");
                    }
                }
                br.close();
                loadinglbl.setText("Done !");
                Thread.sleep(50);
                loading.setVisible(false);
                loadinglbl.setText("");
                setbuttactive();
            } catch (Exception e) {
            }
        }

    }

    void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        datebutt.setText(s.format(d));
    }

    void showtime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm a");
                timelbl.setText(s.format(d));
            }
        }).start();
    }

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        namesearch ns = new namesearch();
        ns.setVisible(true);
    }//GEN-LAST:event_kButton2ActionPerformed

    private void newstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newstuActionPerformed
        // TODO add your handling code here:
        inputstudentsfrm inputstudentsffrm = new inputstudentsfrm();
        inputstudentsffrm.setVisible(true);
    }//GEN-LAST:event_newstuActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
        regsearch reg = new regsearch();
        reg.setVisible(true);
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        fathersearch fs = new fathersearch();
        fs.setVisible(true);
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        rangesearch rs = new rangesearch();
        rs.setVisible(true);
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        datesearch ds = new datesearch();
        ds.setVisible(true);
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        paydues pd = new paydues();
        pd.setVisible(true);
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        showoutdate so = new showoutdate();
        so.setVisible(true);
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        addcourse ac = new addcourse();
        ac.setVisible(true);
    }//GEN-LAST:event_kButton10ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        editentry ee = new editentry();
        ee.setVisible(true);
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        deleteentry de = new deleteentry();
        de.setVisible(true);
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        showdues sd = new showdues();
        sd.setVisible(true);
    }//GEN-LAST:event_kButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new optionsfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton datebutt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.k33ptoo.components.KButton kButton10;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton12;
    private com.k33ptoo.components.KButton kButton13;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private keeptoo.KGradientPanel kGradientPanel1;
    public static javax.swing.JProgressBar loading;
    public static javax.swing.JLabel loadinglbl;
    private com.k33ptoo.components.KButton newstu;
    private javax.swing.JLabel timelbl;
    // End of variables declaration//GEN-END:variables

}
