/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class showdues extends javax.swing.JFrame {

    /**
     * Creates new form showdues
     */
    /*class shdues {

        static int duesvalue2 = 0;
    }*/

    static int duesvalue;

    public showdues() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        slider = new javax.swing.JSlider();
        jLabel22 = new javax.swing.JLabel();
        closebutt = new com.k33ptoo.components.KButton();
        showbutt = new com.k33ptoo.components.KButton();

        setTitle("Show  dues");
        setMinimumSize(new java.awt.Dimension(710, 360));
        setPreferredSize(new java.awt.Dimension(710, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 45, 145));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slider.setBackground(new java.awt.Color(255, 255, 255));
        slider.setMajorTickSpacing(500);
        slider.setMaximum(5000);
        slider.setMinimum(500);
        slider.setMinorTickSpacing(100);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setSnapToTicks(true);
        slider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sliderKeyPressed(evt);
            }
        });
        jPanel2.add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 480, 80));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Select a value : ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 120, -1));

        closebutt.setBorder(null);
        closebutt.setText("Close");
        closebutt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closebutt.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        closebutt.setkEndColor(new java.awt.Color(255, 51, 51));
        closebutt.setkFillButton(false);
        closebutt.setkForeGround(new java.awt.Color(255, 102, 102));
        closebutt.setkHoverForeGround(new java.awt.Color(255, 51, 51));
        closebutt.setkHoverStartColor(new java.awt.Color(204, 0, 0));
        closebutt.setkStartColor(new java.awt.Color(204, 0, 0));
        closebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttActionPerformed(evt);
            }
        });
        jPanel2.add(closebutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, 30));

        showbutt.setBorder(null);
        showbutt.setText("Show");
        showbutt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showbutt.setkBackGroundColor(new java.awt.Color(255, 51, 51));
        showbutt.setkFillButton(false);
        showbutt.setkForeGround(new java.awt.Color(0, 153, 153));
        showbutt.setkHoverForeGround(new java.awt.Color(0, 102, 102));
        showbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttActionPerformed(evt);
            }
        });
        jPanel2.add(showbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttActionPerformed
        showdues.this.hide();
    }//GEN-LAST:event_closebuttActionPerformed

    private void showbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttActionPerformed

        
        duesvalue = slider.getValue();
        
       
        
       // shdues.duesvalue2 = duesvalue;
        duesoutput du = new duesoutput();
        du.setVisible(true);
        

    }//GEN-LAST:event_showbuttActionPerformed

    private void sliderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sliderKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            duesvalue = slider.getValue();
           // shdues.duesvalue2 = duesvalue;
            duesoutput du = new duesoutput();
            du.setVisible(true);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            showdues.this.hide();
        }
    }//GEN-LAST:event_sliderKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showdues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showdues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showdues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showdues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showdues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton closebutt;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.k33ptoo.components.KButton showbutt;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
