/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.shujava.ikon_dtabs_gui_netbeans;

import com.k33ptoo.components.KButton;
import java.awt.Color;
import java.awt.dnd.DragGestureListener;
import keeptoo.KGradientPanel;

import java.awt.dnd.DragSource;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Objects;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author shubh
 */
public class signUpfrm extends javax.swing.JFrame {

    static String usern = "";
    static String pass = "";

    /**
     * Creates new form signUpfrm
     */
    public signUpfrm() {
        initComponents();
        modifyinitComponents();

        try {
            BufferedReader userreader = new BufferedReader(new FileReader("user.txt"));
            BufferedReader passreader = new BufferedReader(new FileReader("pass.txt"));
            usern = userreader.readLine();
            pass = passreader.readLine();
        } catch (Exception e) {

        }
    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            kButton3.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentMoverUtil1 = new com.k33ptoo.utils.ComponentMoverUtil();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        btn_ext = new javax.swing.JLabel();
        usernlbl = new javax.swing.JLabel();
        nwpsstxtfield = new javax.swing.JTextField();
        passlbl = new javax.swing.JLabel();
        warniglbl = new javax.swing.JLabel();
        newpsslbl = new javax.swing.JLabel();
        dltbutt = new com.k33ptoo.components.KButton();
        jTextField2 = new javax.swing.JTextField();
        dltbutt2 = new com.k33ptoo.components.KButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 130));
        setMaximizedBounds(new java.awt.Rectangle(500, 400, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setBackground(new Color(0,0,0,0));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField1.setCaretColor(new java.awt.Color(204, 0, 255));
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        kGradientPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 410, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("or");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, 14));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("password");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 19));

        kButton2.setBorder(null);
        kButton2.setText("Registor");
        kButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton2.setkPressedColor(new java.awt.Color(255, 51, 255));
        kButton2.setkStartColor(new java.awt.Color(204, 0, 204));
        kButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton2MouseClicked(evt);
            }
        });
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 160, 40));

        kButton3.setBorder(null);
        kButton3.setText("Sign In");
        kButton3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton3.setkFillButton(false);
        kButton3.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton3.setkStartColor(new java.awt.Color(255, 255, 255));
        kButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton3MouseClicked(evt);
            }
        });
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 160, 40));

        btn_ext.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_ext.setForeground(new java.awt.Color(255, 255, 255));
        btn_ext.setText("x");
        btn_ext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_extMouseClicked(evt);
            }
        });
        btn_ext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_extKeyPressed(evt);
            }
        });
        kGradientPanel1.add(btn_ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 20, 20));

        usernlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernlbl.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(usernlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 190, 20));

        nwpsstxtfield.setBackground(new Color(0,0,0,0));
        nwpsstxtfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nwpsstxtfield.setForeground(new java.awt.Color(255, 255, 255));
        nwpsstxtfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nwpsstxtfield.setCaretColor(new java.awt.Color(204, 0, 255));
        nwpsstxtfield.setOpaque(false);
        nwpsstxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwpsstxtfieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nwpsstxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 220, -1));

        passlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passlbl.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(passlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 190, 20));

        warniglbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        warniglbl.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(warniglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 250, 20));

        newpsslbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newpsslbl.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(newpsslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 120, 20));

        dltbutt.setBorder(null);
        dltbutt.setText("Delete User");
        dltbutt.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        dltbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbuttActionPerformed(evt);
            }
        });
        kGradientPanel1.add(dltbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 100, 30));

        jTextField2.setBackground(new Color(0,0,0,0));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextField2.setCaretColor(new java.awt.Color(204, 0, 255));
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        kGradientPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 410, -1));

        dltbutt2.setBorder(null);
        dltbutt2.setText("Delete User");
        dltbutt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltbutt2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(dltbutt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 100, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/IKON LOGOs.png"))); // NOI18N
        kGradientPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("username");
        kGradientPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, 14));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shujava/ikon_dtabs_gui_netbeans/icons8-male-user-50.png"))); // NOI18N
        kGradientPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 70, 60));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyinitComponents() {
        dltbutt.setVisible(false);
        newpsslbl.setVisible(false);
        nwpsstxtfield.setVisible(false);
        dltbutt2.setVisible(false);

        try {
            //ImageIcon ICON = new ImageIcon(getClass().getResource("male.png"));
            //jLabel14.setIcon(ICON);
            //jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("male.png")));
            //BufferedImage image = ImageIO.read("C:\Users\shubh\Desktop\icons8-male-user-50.png");
            //jLabel14.setIcon(image);
        } catch (Exception e) {

        }

    }
    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        //new Drag(kGradientPanel1).moveWindow(evt);  

    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        //new Drag(kGradientPanel1).onPress(evt); 

    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton3ActionPerformed

    private void btn_extMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_extMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_extMouseClicked

    private void kButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton3MouseClicked
        // TODO add your handling code here:
        String tempusern = jTextField2.getText();
        String temppass = jPasswordField1.getText();
        if (Objects.equals(usern, tempusern) && Objects.equals(pass, temppass)) {
            passlbl.setText("Correct Password");
            usernlbl.setText("");
            warniglbl.setText("");
            dltbutt.setVisible(false);
            optionsfrm optionsfrm = new optionsfrm();

            optionsfrm.setVisible(true);

            signUpfrm.this.hide();

            //optionsfrm.loadData();
        } else {
            passlbl.setText("                 wrong password");
            dltbutt.setVisible(false);
        }
        if (jPasswordField1.getText().length() == 0) {
            passlbl.setText(" password cannot be empty");
            warniglbl.setText("");
            dltbutt.setVisible(false);
        }
        if (!(Objects.equals(usern, tempusern))) {
            usernlbl.setText("         username did't match");
            passlbl.setText("");
            warniglbl.setText("");
            dltbutt.setVisible(false);
        }
        if (jTextField2.getText().length() == 0) {
            usernlbl.setText("username cannot be empty");
            warniglbl.setText("");
            dltbutt.setVisible(false);
        }
    }//GEN-LAST:event_kButton3MouseClicked

    @SuppressWarnings("empty-statement")
    private void kButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton2MouseClicked
        // TODO add your handling code here:
        boolean check = false;
        dltbutt2.setVisible(false);
        try {
            if (usern.length() > 0) {
                warniglbl.setText("One or more user already exists !");
                dltbutt.setVisible(true);
                check = true;
            }
        } catch (Exception e) {
        }

        if (check == false) {
            if (jTextField2.getText().length() == 0) {
                usernlbl.setText("username cannot be empty");
            } else {
                usern = jTextField2.getText();
                usernlbl.setText("");
                try {
                    BufferedWriter bwuser = new BufferedWriter(new FileWriter("user.txt"));
                    bwuser.write(usern);
                    bwuser.close();
                } catch (Exception e) {
                }
            }
            if (jPasswordField1.getText().length() == 0) {
                passlbl.setText(" password cannot be empty");
            } else {
                pass = jPasswordField1.getText();
                passlbl.setText("");

                try {
                    BufferedWriter bwpass = new BufferedWriter(new FileWriter("pass.txt"));
                    bwpass.write(pass);
                    bwpass.close();
                } catch (Exception e) {
                }
            }
        }

    }//GEN-LAST:event_kButton2MouseClicked

    private void nwpsstxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwpsstxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nwpsstxtfieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void dltbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbuttActionPerformed
        // TODO add your handling code here:
        newpsslbl.setText("Enter password :");
        warniglbl.setVisible(false);
        newpsslbl.setVisible(true);
        nwpsstxtfield.setVisible(true);
        dltbutt.setVisible(false);
        dltbutt2.setVisible(true);
    }//GEN-LAST:event_dltbuttActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void dltbutt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltbutt2ActionPerformed
        // TODO add your handling code here:
        if (Objects.equals(nwpsstxtfield.getText(), pass)) {
            usern = "";
            pass = "";
            nwpsstxtfield.setVisible(false);
            newpsslbl.setVisible(false);
            warniglbl.setText("     User deleted successfully");
            warniglbl.setVisible(true);
            dltbutt2.setVisible(false);
            try {
                BufferedWriter bwuser = new BufferedWriter(new FileWriter("user.txt"));
                BufferedWriter bwpass = new BufferedWriter(new FileWriter("pass.txt"));
                bwuser.write("");
                bwpass.write("");
                bwuser.close();
                bwpass.close();
            } catch (Exception e) {
            }

        } else {
            nwpsstxtfield.setVisible(false);
            newpsslbl.setVisible(false);
            warniglbl.setText("          Wrong password");
            warniglbl.setVisible(true);
            dltbutt2.setVisible(false);
        }
    }//GEN-LAST:event_dltbutt2ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String tempusern = jTextField2.getText();
            String temppass = jPasswordField1.getText();
            if (Objects.equals(usern, tempusern) && Objects.equals(pass, temppass)) {
                passlbl.setText("Correct Password");
                usernlbl.setText("");
                warniglbl.setText("");
                dltbutt.setVisible(false);
                optionsfrm optionsfrm = new optionsfrm();

                optionsfrm.setVisible(true);

                signUpfrm.this.hide();

                //optionsfrm.loadData();
            } else {
                passlbl.setText("                 wrong password");
                dltbutt.setVisible(false);
            }
            if (jPasswordField1.getText().length() == 0) {
                passlbl.setText(" password cannot be empty");
                warniglbl.setText("");
                dltbutt.setVisible(false);
            }
            if (!(Objects.equals(usern, tempusern))) {
                usernlbl.setText("         username did't match");
                passlbl.setText("");
                warniglbl.setText("");
                dltbutt.setVisible(false);
            }
            if (jTextField2.getText().length() == 0) {
                usernlbl.setText("username cannot be empty");
                warniglbl.setText("");
                dltbutt.setVisible(false);
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void btn_extKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_extKeyPressed

    }//GEN-LAST:event_btn_extKeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUpfrm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ext;
    private com.k33ptoo.utils.ComponentMoverUtil componentMoverUtil1;
    private com.k33ptoo.components.KButton dltbutt;
    private com.k33ptoo.components.KButton dltbutt2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel newpsslbl;
    private javax.swing.JTextField nwpsstxtfield;
    private javax.swing.JLabel passlbl;
    private javax.swing.JLabel usernlbl;
    private javax.swing.JLabel warniglbl;
    // End of variables declaration//GEN-END:variables

    private void jLabel14(ImageIcon ICON) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /*
    private void DragSource(KGradientPanel kGradientPanel1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     */
}
